// Import and register all your controllers from the importmap via controllers/**/*_controller
import { application } from "controllers/application";
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading";
eagerLoadControllersFrom("controllers", application);

// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

// import { application } from "./application";

// import DebounceController from "./debounce_controller";
// application.register("debounce", DebounceController);

// import HelloController from "./hello_controller";
// application.register("hello", HelloController);

// import { lazyLoadControllersFrom } from "@hotwired/stimulus-loading";
// lazyLoadControllersFrom("controllers", application);
